version: "3"
services:
  flask-app:
    image: docker.swalha.com/flask-project:1.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
